# Generated by Django 5.1.4 on 2026-09-24 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='赛事名称')),
                ('description', models.CharField(blank=True, default='', max_length=400, verbose_name='说明')),
                ('start_time', models.DateTimeField(verbose_name='开赛时间')),
                ('cutoff_time', models.DateTimeField(verbose_name='打卡截止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'event',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, verbose_name='点位编号')),
                ('name', models.CharField(max_length=80, verbose_name='点位名称')),
                ('clue', models.CharField(blank=True, default='', max_length=255, verbose_name='线索/任务')),
                ('required', models.BooleanField(default=True, verbose_name='是否必达')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='建议顺序')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='domain.event')),
            ],
            options={
                'db_table': 'checkpoint',
                'ordering': ['order', 'id'],
                'unique_together': {('event', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='队名')),
                ('leader_name', models.CharField(max_length=40, verbose_name='领队姓名')),
                ('contact', models.CharField(blank=True, default='', max_length=60, verbose_name='联系方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='domain.event')),
            ],
            options={
                'db_table': 'team',
                'ordering': ['created_at', 'id'],
                'unique_together': {('event', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='姓名')),
                ('number', models.CharField(blank=True, default='', max_length=24, verbose_name='号码布/编号')),
                ('is_leader', models.BooleanField(default=False, verbose_name='是否领队')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='domain.team')),
            ],
            options={
                'db_table': 'member',
                'ordering': ['-is_leader', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdjustmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('judge_punch', '裁判补记'), ('revoke', '撤销有效打卡'), ('window', '调整赛事时间')], max_length=16)),
                ('detail', models.CharField(max_length=500, verbose_name='调整内容')),
                ('operator', models.CharField(blank=True, default='裁判', max_length=40, verbose_name='操作裁判')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('checkpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_logs', to='domain.checkpoint')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_logs', to='domain.event')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_logs', to='domain.team')),
            ],
            options={
                'db_table': 'adjustment_log',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Punch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(blank=True, default='', max_length=40, verbose_name='提交成员')),
                ('source', models.CharField(choices=[('member', '成员打卡'), ('judge', '裁判补记')], default='member', max_length=10)),
                ('result', models.CharField(choices=[('valid', '有效'), ('rejected', '已拒绝')], default='valid', max_length=10)),
                ('reject_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='拒绝原因')),
                ('punch_time', models.DateTimeField(verbose_name='到达时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('judge_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='裁判补记原因')),
                ('evidence', models.CharField(blank=True, default='', max_length=255, verbose_name='凭证说明')),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punches', to='domain.checkpoint')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punches', to='domain.team')),
            ],
            options={
                'db_table': 'punch',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('result', 'valid')), fields=('team', 'checkpoint'), name='uniq_valid_punch_per_team_cp')],
            },
        ),
    ]
