# Generated by Django 5.1.4 on 2026-09-24 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('difficulty', models.CharField(choices=[('family', '亲子'), ('adult', '成人'), ('pro', '专业')], default='adult', max_length=16)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'or_event',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=80)),
                ('seq', models.PositiveIntegerField(default=1)),
                ('clue', models.CharField(blank=True, default='', max_length=300)),
                ('required', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='domain.event')),
            ],
            options={
                'db_table': 'or_checkpoint',
                'ordering': ['seq', 'id'],
                'unique_together': {('event', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('leader_name', models.CharField(max_length=60)),
                ('contact', models.CharField(blank=True, default='', max_length=60)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='domain.event')),
            ],
            options={
                'db_table': 'or_team',
                'ordering': ['number'],
                'unique_together': {('event', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('number', models.CharField(blank=True, default='', max_length=20)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='domain.team')),
            ],
            options={
                'db_table': 'or_member',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(blank=True, default='', max_length=60)),
                ('action', models.CharField(choices=[('backfill', '补记漏打'), ('revoke', '撤销补记')], default='backfill', max_length=16)),
                ('reason', models.CharField(max_length=500)),
                ('evidence', models.CharField(blank=True, default='', max_length=500)),
                ('checkin_time', models.DateTimeField(blank=True, null=True)),
                ('operator', models.CharField(default='裁判', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='domain.checkpoint')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='domain.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='domain.team')),
            ],
            options={
                'db_table': 'or_adjustment',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('source', models.CharField(choices=[('member', '选手打卡'), ('referee', '裁判补记')], default='member', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjustment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin', to='domain.adjustment')),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='domain.checkpoint')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='domain.member')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='domain.team')),
            ],
            options={
                'db_table': 'or_checkin',
                'ordering': ['time'],
                'unique_together': {('team', 'checkpoint')},
            },
        ),
    ]
